(cl:defpackage thesis_realsense-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "GRIPPERDATA"
   "<GRIPPERDATA-REQUEST>"
   "GRIPPERDATA-REQUEST"
   "<GRIPPERDATA-RESPONSE>"
   "GRIPPERDATA-RESPONSE"
  ))

