// Generated by gencpp from file thesis_realsense/AddTwoInts.msg
// DO NOT EDIT!


#ifndef THESIS_REALSENSE_MESSAGE_ADDTWOINTS_H
#define THESIS_REALSENSE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <thesis_realsense/AddTwoIntsRequest.h>
#include <thesis_realsense/AddTwoIntsResponse.h>


namespace thesis_realsense
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace thesis_realsense


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::thesis_realsense::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::thesis_realsense::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::thesis_realsense::AddTwoInts > {
  static const char* value()
  {
    return "thesis_realsense/AddTwoInts";
  }

  static const char* value(const ::thesis_realsense::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::thesis_realsense::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::thesis_realsense::AddTwoInts > 
template<>
struct MD5Sum< ::thesis_realsense::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::thesis_realsense::AddTwoInts >::value();
  }
  static const char* value(const ::thesis_realsense::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::thesis_realsense::AddTwoIntsRequest> should match 
// service_traits::DataType< ::thesis_realsense::AddTwoInts > 
template<>
struct DataType< ::thesis_realsense::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::thesis_realsense::AddTwoInts >::value();
  }
  static const char* value(const ::thesis_realsense::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::thesis_realsense::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::thesis_realsense::AddTwoInts > 
template<>
struct MD5Sum< ::thesis_realsense::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::thesis_realsense::AddTwoInts >::value();
  }
  static const char* value(const ::thesis_realsense::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::thesis_realsense::AddTwoIntsResponse> should match 
// service_traits::DataType< ::thesis_realsense::AddTwoInts > 
template<>
struct DataType< ::thesis_realsense::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::thesis_realsense::AddTwoInts >::value();
  }
  static const char* value(const ::thesis_realsense::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THESIS_REALSENSE_MESSAGE_ADDTWOINTS_H
